### ISSUE TITLE
BaseModel.validate() is a confusing method name, need to consider a different name.

### ISSUE THREAD

**Issue by dotDeeka** [NextStepLiving/ts-validator#4]
the method validate in BaseModel returns an map of error messages for the given model, or null if there are no errors. This behavior seems confusing to me if you want to call .validate() in a submit handler for instance.

Consider the following code, a controller with an onSubmit handler
```typescript
import { PersonModel } from './person-model';

export class AddPersonController {
    
    public personModel: PersonModel;
    
    constructor() {
        this.personModel = new PersonModel();
    }
    
    public onFormSubmit() {
        if (this.personModel.validate()) {
            // will execute true block if there are errors
        } else {
            // will execute false block if there are not errors
        }
    }
}
```

The logic above feels backwards.

cc/ @joshschaeffer

**Comment by joshschaeffer** [comment]
rename it hasErrors() or something closer to its actual use

**Comment by dotDeeka** [comment]
I feel like hasErrors() implies that it will return a boolean. I was thinking getErrors()

**Comment by joshschaeffer** [comment]
:+1:
